---
kind: Service
apiVersion: v1
metadata:
  name: github-scraper-service
spec:
  selector:
    app.kubernetes.io/name: github-scraper
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-scraper-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: github-scraper
  template:
    metadata:
      labels:
        app.kubernetes.io/name: github-scraper
    spec:
      containers:
        - name: github-scraper
          image: githubscrapercontainer.azurecr.io/github-scraper:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: azurecr
